kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "chart.name" . }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.istio.io"]
  resources: ["gateways", "serviceentries", "workloadentries", "destinationrules", "virtualservices"]
  verbs: ["get", "create", "update"]
