apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc-mcp
      port: 15010
      targetPort: grpc-mcp
      protocol: TCP
    - name: grpc-fds
      port: 15080
      targetPort: grpc-fds
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
  - name: grpc-fds
    port: 15080
    targetPort: grpc-fds
    protocol: TCP
    appProtocol: grpc
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
